## Martin Flodén: Teaching

### Intermediate Macroeconomics
- [EC2211 Intermediate Macroeconomics](https://www.su.se/english/education/course-catalogue/ec/ec2211)
- Undergraduate
- I teach the fall-semester version of this course
- Contents (Fall 2025):
  - Measuring the macroeconomy
  - Economic growth and the Solow model
  - More growth: human capital, finite natural resources, Malthus
  - TFP and long-term growth: the Romer model
  - Labor supply and unemployment
  - Consumption and investment
  - The short run: IS-MP and the Phillips curve
  - The short run: AS-AD, the Taylor rule, the time-inconsistency problem
  - Money and monetary policy
  - Government debt and fiscal policy
  - Exchange rates and international finance
  - Open economy macroeconomics and the international monetary system


### Master's course in macroeconomics
- [EC7210 Macroeconomics](https://www.su.se/english/education/course-catalogue/ec/ec7210)
- Compulsory first-semester course in the Master's program
- The listed textbook for the course is David Romer's "Advanced Macroeconomics" but it is mostly used as background reading
- I provide detailed lecture notes for all theoretical material covered
- Contents (Fall 2025):
  - Consumption theory
  - The neoclassical growth model
  - The overlapping generations model
  - The real business cycle model
  - The new keynesian business cycle model
  - Monetary policy rules and the transmission of monetary policy
  - Topics in monetary policy
  - Public debt and fiscal policy





